name: Scheduled GCP Scan

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 0'  # every Sunday at 03:00 UTC

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate to GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > sa.json
          gcloud auth activate-service-account --key-file=sa.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Run scanner
        run: |
          python3 -m scanner.scanner \
            --project="${{ secrets.GCP_PROJECT_ID }}" \
            --output="report-${{ github.run_id }}.json"

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: gcp-scan-report
          path: report-*.json
